### ISSUE TITLE
Upgrade and downgrade issues with 1.1.38

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#1541]
Two major problems with 1.1.38.

First: after upgrading from 1.1.37 to 1.1.38 the poller is going to recache hosts and keeps on doing that every polling cycle. This is resulting in having no more data added to my graphs. He keeps on detecting recache events and also shows comparisons of values.

Maybe some usefull side info: My poller is set to 5 minutes (cron and setting).

Second; downgrading is not possible because of an error. “Unable to download from 1.1.38$ to 1.1.37 because version is invalid” (or something similar). I noticed there was an odd version shown with the dollar sign.

Because there are no database changes in 1.1.38, I’ve just changed the record in the version table to 1.1.37. But that’s ofcourse not how it’s supposed to be going.

**Comment by netniV** [comment]
There seems to be a $ symbol in your version number.  Is that a typo or did it actually display that?  If so, there's a bug crept in somewhere.

**Comment by reboot1983** [comment]
It’s there in the downgrade message (noticed it directly).

Btw; my quote shows ‘download’ this should be downgrade.. my bad 🤕

**Comment by netniV** [comment]
Was it in the database that way? or have you already replaced the value without checking?

**Comment by reboot1983** [comment]
The value (1.1.38) was correct in the database table. It did not mention the $ symbol.

Btw; just noticed that all stats are functioning correctly again after downgrading back to 1.1.37

**Comment by ronytomen** [comment]
Double checked, no extra chars (non-visible either) appear in the release.

Can you elaborate on what happened that caused you to downgrade?

**Comment by ntphuoc1990** [comment]
Hi everybody,
I'm a newbie here and my English is very bad.
I've just installed Cacti 1.1.38 on my CentOS 7 with Apache2.4 Mariadb10.2 and MyPHP7.1 follow this instruction: https://www.vultr.com/docs/how-to-install-cacti-1-1-on-centos-7
But when I accessed to "http://ip_address/cacti", I got HTTP Error 500.
I tried to open the log file and I found the error logs as below:

> Tue Apr 17 11:32:49.107846 2018] [php7:warn] [pid 1536] [client 172.16.100.250:53609] PHP Warning:  include(/opt/cacti-1.1.38/include/auth.php): failed to open stream: Permission denied in /opt/cacti-1.1.38/index.php on line 25
[Tue Apr 17 11:32:49.107979 2018] [php7:warn] [pid 1536] [client 172.16.100.250:53609] PHP Warning:  include(): Failed opening './include/auth.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /opt/cacti-1.1.38/index.php on line 25
[Tue Apr 17 11:32:49.108178 2018] [php7:error] [pid 1536] [client 172.16.100.250:53609] PHP Fatal error:  Uncaught Error: Call to undefined function top_header() in /opt/cacti-1.1.38/index.php:26\nStack trace:\n#0 {main}\n  thrown in /opt/cacti-1.1.38/index.php on line 26

I tried to chmod 777 on folder opt/cacti-1.1.38 ( I'm a newbie in Linux too, everything in linux is totally fresh to me ) then restarted httpd service but it didn't help.

Please anybody give me a good instruction to install cacti 1.137 or 1.1.38 on Ubuntu 16.04 or Centos 7.
I used to install Cacti on Ubuntu 16.04 but it was jut 0.88f version, when I upgrade to 1.1.37, it was failed.

**Comment by reboot1983** [comment]
I've just upgraded and downgraded again and now I've got the screencapture of the error message. (it also is reproducable, just downgrade and you'll get  the error).

This is the Dutch error message.
![image](https://user-images.githubusercontent.com/20405704/38888894-43859700-427d-11e8-88cf-32e3e0d5b584.png)

The original english version is: 
```Invalid Cacti version <strong>%1$s</strong>, cannot upgrade to <strong>%2$s</strong>```

This is translated to:
```Ongeldige Cacti versie <strong>%s$s</strong>, kan niet upgraden naar <strong>%2$s</strong>```
but should be translated as:
```Ongeldige Cacti versie <strong>%1$s</strong>, kan niet upgraden naar <strong>%2$s</strong>```

Notice the %s$s which should be translated to %1$s. This is probably my bad, and a mistake in the translation. But this is only the text showing a wrong character.

Although the code seems to notice there is a plan for downgrading, and also warns that the database will not be rolled back and data corruption is possible, it fails to downgrade Cacti. I'm not sure and am not able to fix or test the code, but it looks like install/index.php#336 and further fails on this part of the code:

```
/* upgrade */
} elseif (($step == '8') && (get_filter_request_var('install_type') == '3')) {
	// if the version is not found, die
	if (!array_key_exists($old_cacti_version, $cacti_version_codes)) {
		print "	<p style='font-family: Verdana, Arial; font-size: 16px; font-weight: bold; color: red;'>" . __('Error') . "</p>
			<p style='font-family: Verdana, Arial; font-size: 12px;'>"
			. __('Invalid Cacti version <strong>%1$s</strong>, cannot upgrade to <strong>%2$s</strong>', $old_cacti_version, CACTI_VERSION) . "</p>";
		exit;
	}
```
I'm unable to fix the translations or apply a patch for the downgrade at this moment. Maybe someone else is available for this?

**Comment by netniV** [comment]
Good spot on the message problem.  I did a 1.1.38 upgrade this morning without issues.  This makes me wonder what is different in your setup to cause you a problem.

**Comment by reboot1983** [comment]
@netniV Is there anything I can show you, tell you or provide you with?

**Comment by netniV** [comment]
Just looking at the asserts, I'm wondering if it's those values getting converted wrongly.

**Comment by cigamit** [comment]
@reboot1983, need to know the following:

`php --version`
`php -m`

Then, if php-snmp is installed, uninstall it.  See if that makes a difference.

**Comment by reboot1983** [comment]
```
pi@raspberrypi:~ $ php --version
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

pi@raspberrypi:~ $ php -m
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

I'll try to do another upgrade without php-snmp this evening or tomorrow evening.

**Comment by cigamit** [comment]
php-snmp needs a major facelift.  No time though.

**Comment by reboot1983** [comment]
I was just be able to give this a try. 
First I disabled php-snmp by running:
```phpdismod snmp```

Then I waited a few polling-cycles to see what would happen. First thing I noticed is that the poller seems to be about 50% slower now. (But still more than quick enough for my small environment).

Then I toggled the symlink to 1.1.38 and waited another few moments. Everything seems to be OK and I'm running cacti 1.1.38 now. 😄 

![image](https://user-images.githubusercontent.com/20405704/39117692-d620f35c-46e7-11e8-8776-5f37788d6ca7.png)

The first polling cycle without php-snmp was at 10:55. You can notice an increase of the poller time here.

The first polling cycle without php-snmp and running 1.1.38 was at 11:05. You can still notice an increase of the poller time. 

So:
1. The poller-process is about 50% slower without php-snmp, (but at least it's working on 1.1.38);
2. The downgrade process seems to have issues and is unwilling to downgrade Cacti;
3. There is a typo in the Dutch language file with the errormessage.

**Comment by cigamit** [comment]
Well, that is pretty cool.  Talk about correlation.  Likely heating the man cave too.  As much as I don't want to have to do more testing with php-snmp enabled, I guess I will have to.  Have to match versions though.  I have all I need.  Now I just need to make a time window to do the testing.  Also, using spine should avoid this issue and cool the man cave.

**Comment by cigamit** [comment]
I have fixed this in an update cmd.php for Non-spine behavior.  Simply pull cmd.php from the develop branch.

**Comment by Lucutuz** [comment]
Hi, I am sorry but after pulling cmd.php from develop branch all my graphs are getting empty. With the cmd.php from 1.1.38 I only have some hosts with empty graphs.

**Comment by cigamit** [comment]
Okay, then also pull lib/snmp.php and include/vendor/phpsnmp/classSNMP.php also.

**Comment by Lucutuz** [comment]
Still no luck, cacti.log nearly empty:

2018/06/05 14:20:00 - POLLER: Poller[1] Maximum runtime of 58 seconds exceeded. Exiting.
2018/06/05 14:20:00 - SYSTEM STATS: Time:58.3838 Method:cmd.php Processes:20 Threads:N/A Hosts:97 HostsPerProcess:5 DataSources:5171 RRDsProcessed:0
2018/06/05 14:20:07 - SYSTEM Reports STATS: Time:6.9954 Reports:3

I have never configured such a maximum runtime?

**Comment by netniV** [comment]
The maximum runtime of the poller is determined by your data profiles and the cron file

**Comment by Lucutuz** [comment]
IHi,

ok, i tried now the 1.1.38 from tar.gz file. I needed to disable snmp in php

php5dismod snmp

Now it seems to work for the failed devices. But it is slow.
So i wanted to downgrade to 1.1.37 but it gives me an error.
I read here that i have to change something with the "version table" what exactly do i have to do? Is the MySQL-Table "version" meant? There is "1.1.38" in.

**Comment by wencagh** [comment]
There is other solution. You can only replace file cmd.php from package ver 1.1.38 by 1.1.37
Problem is propably "bad/uncomplete" fix in 1.1.38
issue#1501: cmd.php poller not stripping alpha from snmp get values
https://github.com/Cacti/cacti/commit/636a277324331364d0dcf86d230683f47ca0111a
