### ISSUE TITLE
Graph permission not working сorrectly

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#235]
The filter not have Interface-Traffic and graphics are not displayed in the device with a template Interface-Traffic. If added separately into a tree, the graph shows.
![graph-tree2](https://cloud.githubusercontent.com/assets/11805503/22339197/d533c618-e3f1-11e6-93b5-1293d9f733c2.png)
![graph-tree1](https://cloud.githubusercontent.com/assets/11805503/22339198/d5346b22-e3f1-11e6-96f8-656f6767bfc3.png)

**Comment by pautiina** [comment]
Maybe in ./lib/auth.php file - a mistake.
When I change a value in a row in 1139 type
```
$ Sql_join. = 'LEFT JOIN user_auth_'. ($ Policy [ 'type'] == 'user' '?': 'Group_'). "Perms AS uap $ i ON (gt.graph_template_id = uap $ i.item_id AND uap $ i.type = 4)";
$ Sql_join. = 'LEFT JOIN user_auth_'. ($ Policy [ 'type'] == 'user' '?': 'Group_'). "Perms AS uap $ i ON (gt.graph_template_id = uap $ i.item_id AND uap $ i.type != 4)";
```

That all works and graphics are displayed in a tree.

**Comment by cigamit** [comment]
The code you pasted makes no sense.

**Comment by pautiina** [comment]
I change my code, i'm find probleb? but dont know hove to fix that:

> Maybe in ./lib/auth.php file row 1339 a mistake.
> $sql_join .= 'LEFT JOIN user_auth_' . ($policy['type'] == 'user' ? '':'group_') . "perms AS uap$i ON (gt.graph_template_id=uap$i.item_id AND uap$i.type=4) ";
> 
> When one user is denied access to the graph, it is forbidden to all users.
> If you delete from table user_auth_perms user, the graphics are again available to all users.

**Comment by cigamit** [comment]
You will need to provide a detailed case on how to reproduce.  Be very specific.

**Comment by cigamit** [comment]
Pautiina, I was thinking of the same thing.  The design was to have the HAVING SQL cover that case, but maybe it is flawed.  However, provide the detailed steps to reproduce.  Thanks.

**Comment by pautiina** [comment]
I have two users. The first administrator of the second user in whose have Graph_perms "Default Graph Policy for this User" = deny- then the administrator is also is forbidden access to the same schedule, which are forbidden the user.

**Comment by pautiina** [comment]
![1](https://cloud.githubusercontent.com/assets/11805503/22387563/e483dbdc-e4e4-11e6-8100-1fa8393f09f6.png)
![2](https://cloud.githubusercontent.com/assets/11805503/22387564/e483f39c-e4e4-11e6-9c60-7738c820366f.png)
![3](https://cloud.githubusercontent.com/assets/11805503/22387565/e4851524-e4e4-11e6-92fd-b4afe7f12d7d.png)

**Comment by cigamit** [comment]
Please test.  This should be resolved.  Permissions should be much faster for larger systems as well.

**Comment by pautiina** [comment]
OK, I check tomorrow,  and write the results.

**Comment by cigamit** [comment]
Please note that if you have access to at least one graph for a device, you will see the Device in the Tree View.  That is as designed.  Same applies to List View and Preview modes.

I'm pretty sure the logic is good at this point.  However, if you find anything, please update this ticket.  I'll keep it open for a few more days.

Remember that there are two graph permission modes:

* 'Restrictive' - Where you need either access to the Graph or a combination of the Device and Graph Template to view the Graph either at the user or group view.  Note that if a users permission blocks, but the groups permission allows, the user will gain access.
* 'Permissive' - Where you simply need access to the Graph Template, or the Device to gain access to all it's Graphs.  Again, the statement on users vs. groups applies.

This is a fundamental change to the Graph permission that were in earlier version of Cacti that were hard to manage, completely ambiguous and misleading in many cases.

**Comment by pautiina** [comment]
The problem is not solved.
The administrator now sees graphs, but a limited user sees graphs and other devices, which are placed in a tree and allowed access to the tree, but only one device with this tree.
![1](https://cloud.githubusercontent.com/assets/11805503/22406634/1287a0e2-e65f-11e6-85da-b1cf66f5fd56.png)
![2](https://cloud.githubusercontent.com/assets/11805503/22406635/128a2600-e65f-11e6-8d59-baee870a41d2.png)
![3](https://cloud.githubusercontent.com/assets/11805503/22406636/128a8cf8-e65f-11e6-8208-1feddbc17e55.png)
![4](https://cloud.githubusercontent.com/assets/11805503/22406639/128eb9b8-e65f-11e6-99fa-91ac2010889f.png)
![5](https://cloud.githubusercontent.com/assets/11805503/22406638/128c2540-e65f-11e6-800f-6d5d989f82fe.png)
![6](https://cloud.githubusercontent.com/assets/11805503/22406637/128b3356-e65f-11e6-89cd-6ad222338e78.png)

**Comment by cigamit** [comment]
Note, Tree permissions do not affect Graph permission.  On the Graph Perms page, what happens if you revoke access at the Graph level?

**Comment by cigamit** [comment]
It also looks as if you are in 'Permissive' mode.  You should try 'Restrictive'.

**Comment by cigamit** [comment]
Looks like the Templates row count is a real issue.  That will have to be addressed.

**Comment by cigamit** [comment]
Fixed the Templates count.  We have already cut the 1.0.0 release tag.  So, you will have to grab the fix from the development branch.

**Comment by pautiina** [comment]
Nothing happens if i revoke permission for graphics. Graphs still displayed. Only if i cancel permission for the template and allow the graph in Graph Perms, the graphics are not showing. Note that the Default Graph Policy for User is default I DENY.
![1](https://cloud.githubusercontent.com/assets/11805503/22407093/61dd800e-e668-11e6-9147-d60a08096c02.png)
![2](https://cloud.githubusercontent.com/assets/11805503/22407094/61f92016-e668-11e6-8e27-6f1725c70b09.png)
![3](https://cloud.githubusercontent.com/assets/11805503/22407095/620dffa4-e668-11e6-9677-256288a5f041.png)

**Comment by cigamit** [comment]
pautiina,

You are still using 'Permissive' settings.  Also, you are mixing too many issues without enough information.  Please read my prior note on how Graph permissions work in this release.  I suggest you use 'Restrictive' Graph permissions.  I'll continue to look into some corner cases though.

**Comment by pautiina** [comment]
I have carefully read your message. I understand. everything works as it is necessary to test and such. I think you can close tikket. Thank you.

**Comment by cigamit** [comment]
Thanks for all your testing.  I would have been nice to get that last issue as part of the release, but people will be able to download the updates if they have issues.  We were able to get two bugs out of the way anyway, and we appreciate your help.  Once you are more comfortable with the new Graph permission system, if you find another issue, please open a second ticket.  And again, thanks for your testing efforts!
