### ISSUE TITLE
Remote poller inconsistent results

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#2671]
I have a new remote poller with two devices configured. one is getting results as expected, while the other host is not generating graphs. permissions to the rra folder/s appear the same. The host shows as 'up' but i'm not getting any graphs. realtime graphs work as well.
I have done a full sync of the remote poller with no luck.

I checked the hostname of the RP and did a successful connection test from the DC page

I'm new to remote pollers so any help would be greatly appreciated.

**Comment by KnoAll** [comment]
Now after about 5 hours, it has started working. I have checked the poller refresh and it is set to 30m (and i did a force sync) not sure exactly how this all works i guess.

**Comment by cigamit** [comment]
Was the Data Collector reporting up from the UI?  If so, what was in the logs on the remote side?

**Comment by KnoAll** [comment]
It shows as 'online' on the remote node. It shows as current like the other pollers in the central ui. 
It does poll another device and the results show as expected on the central UI.
I am not finding any errors or results for the problem device.

**Comment by KnoAll** [comment]
Sorry, still getting inconsistent results. Don't see any pattern on devices that are polled as expected and those that dont

**Comment by KnoAll** [comment]
OK, i have some of the incosistencies ironed out and it was SNMP security in one case. 

But I am still seeing some weird results with remote pollers. Regardless of the sync time that is set, it still takes just about exactly 2 hours for graphs to start populating when switching a device from the main poller over to the remote poller.

**Comment by cigamit** [comment]
Note, in the latest Cacti 1.2, Full Sync should very infrequently be required.  In fact, running it when you don't need to can cause devices not to poll for around one polling cycle.  However, nothing should take as long as you described to run.  I had asked you for your logs from the remote data collector around the time you made the change and before, and have not seen that yet.  What's up?

**Comment by KnoAll** [comment]
Apologies, I'll have to pull them the next time I make a change. 
A couple things I have noticed about the remote poller though. Whenever I'm in the console I see this in the top left corner of the UI.
![image](https://user-images.githubusercontent.com/7632685/57629379-91797380-7550-11e9-9b28-75ab0292078c.png)
Another thing is that there are a lot of errors regarding plugins.

2019/05/13 07:30:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[165]:syslog_config_insert(), /plugins/syslog/setup.php[1003]:syslog_check_upgrade(), /plugins/syslog/setup.php[184]:syslog_connect(), /plugins/syslog/setup.php[170]:CactiErrorHandler())
--
2019/05/13 07:30:26 - ERROR PHP NOTICE in Plugin 'syslog': Undefined variable: syslogdb_type in file: /var/www/html/cacti/plugins/syslog/setup.php on line: 170
2019/05/13 07:30:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[165]:syslog_config_insert(), /plugins/syslog/setup.php[1003]:syslog_check_upgrade(), /plugins/syslog/setup.php[184]:syslog_connect(), /plugins/syslog/setup.php[170]:CactiErrorHandler())
2019/05/13 07:30:26 - ERROR PHP NOTICE in Plugin 'syslog': Undefined variable: syslogdb_default in file: /var/www/html/cacti/plugins/syslog/setup.php on line: 170
2019/05/13 07:30:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[165]:syslog_config_insert(), /plugins/syslog/setup.php[1003]:syslog_check_upgrade(), /plugins/syslog/setup.php[184]:syslog_connect(), /plugins/syslog/setup.php[170]:CactiErrorHandler())
2019/05/13 07:30:26 - ERROR PHP NOTICE in Plugin 'syslog': Undefined variable: syslogdb_password in file: /var/www/html/cacti/plugins/syslog/setup.php on line: 170
2019/05/13 07:30:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[27]:include(), /include/auth.php[28]:require_once(), /include/global.php[484]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[165]:syslog_config_insert(), /plugins/syslog/setup.php[1003]:syslog_check_upgrade(), /plugins/syslog/setup.php[184]:syslog_connect(), /plugins/syslog/setup.php[170]:CactiErrorHandler())
2019/05/13 07:30:26 - ERROR PHP NOTICE in Plugin 'syslog': Undefined variable: syslogdb_username in file: /var/www/html/cacti/plugins/syslog/setup.php on line: 170

**Comment by KnoAll** [comment]
I have a log I can send you. How should I get it to you privately?

**Comment by KnoAll** [comment]
I think I have found one of my biggest issues with remote pollers is Timezone.  I must have missed something in the TZ setup for the remote poller. When polling a device from the main poller vs the remote poller (local to the device) there is a 2 hour difference.
![image](https://user-images.githubusercontent.com/7632685/57902427-eac9f700-781d-11e9-8a55-17d2dd9aa043.png)
I double checked the OS and PHP timezone settings for the remote poller all set to the same as the collector setting in cacti.

Perhaps I'm missing something

**Comment by cigamit** [comment]
Setting up the timezones very important.  Also, the other error was due to the syslogs config.php not being setup properly.

**Comment by cigamit** [comment]
The connect issue is that your main cacti Database does not have access to the remote databases.  You should 'test the connection' for all your remove pollers.  The mysql connection is required to be bidirectional.

**Comment by KnoAll** [comment]
I have tested the bi-direction connection and everything is working.  (both from the UI and cli for good measure) 
I did not deliberately setup the syslog connectivity (different database) so I'll update that.

**Comment by KnoAll** [comment]
What should I check on the timezone settings?

**Comment by cigamit** [comment]
Yes, they must be correct on the main poller.  After which, do a full sync since they may have been incorrect originally.  Depending on the timezone you are coming from, the graphs may stop updating for the difference in timezone between the collectors.  We need a documentation step in the Troubleshooting document on this one too.  I did not even realize what was going on ;)

**Comment by KnoAll** [comment]
I'm very curious about how this all works. I am seeing the difference in timezone and am not sure I understand how/why. It can be confusing when looking at the graphs and not seeing the same timeframe. Maybe i'll put everything to the TZ of the main poller.

**Comment by cigamit** [comment]
Okay, basically, for every remote data collector, you need to get the systems timezone setting.  Then, edit the Data Collector on the Cacti Side and set the very same timezone for it.  Once this is done, the data collection should be correct for both sides.  What Cacti does is that when the Remote Data Collector connects to the central Data Collector, it set's a session variable to it's timezone.  That way timestamps that are sent to the server are corrected for the timezone.

I hope this makes sense.  If there are still issues, then please reopen and we can discuss where you left off.

**Comment by KnoAll** [comment]
OK, I am still seeing this bizarre behavior. I double checked the system timezone is set to America/Chicago (2hr ahead of main poller), the very same in cli/apache php.ini, as well as on the data collector settings.
I set the timeframe on the graphs to show the entire day to be sure i'm seeing everything.
![image](https://user-images.githubusercontent.com/7632685/62983539-8864a080-bde4-11e9-9899-ae9d0884e0a8.png)
