### ISSUE TITLE
Import DataQuery show PHP Error: ERROR PHP NOTICE: Undefined index: fname

### ISSUE THREAD

**Issue by datatecuk** [Cacti/cacti#3871]
# Describe the bug

Import DataQuery show PHP Error: ERROR PHP NOTICE: Undefined index: fname in file: /var/www/cacti/lib/import.php on line: 1798
CMDPHP PHP ERROR NOTICE Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[194]:xml_to_data_input_method(), /lib/import.php[1743]:compare_data(), /lib/import.php[1798]:CactiErrorHandler())

## To Reproduce

1. Go to Console->Import/Export-->Import Templates

2. Click "Select a File" and choose the file you want to import that contains a Data Query

3. Disable "Preview Import Only"

4. Click "Import"

5. See onscreen popup error 

6. Check "Logs" tab, this should contain something like the following
```
DBCALL ERROR: SQL Save on table 'data_input_fields': Column 'fname' does not exist, unable to save!
CMDPHP PHP ERROR NOTICE Backtrace: (/templates_import.php[43]:form_save(), /templates_import.php[97]:import_xml_data(), /lib/import.php[194]:xml_to_data_input_method(), /lib/import.php[1743]:compare_data(), /lib/import.php[1798]:CactiErrorHandler())
ERROR PHP NOTICE: Undefined index: fname in file: /var/www/cacti/lib/import.php on line: 1798
```

7. See Error

## Additional context

This looks like it is related to issue #3778.

**Comment by datatecuk** [comment]
This also happens on a Device Template import that contains a Data Query.

**Comment by TheWitness** [comment]
This is already fixed in the 1.2.x branch and will be a part of the 1.2.15 release.

**Comment by datatecuk** [comment]
I've just tested on the 1.2.x branch and its not working.
It only happens if you have a device template that contains a Data Query.

**Comment by TheWitness** [comment]
Oh, I see now.  Take just a few minutes to fix.

**Comment by datatecuk** [comment]
We are running v1.2.15 and the error comes up as
![image](https://user-images.githubusercontent.com/5603694/96482281-aa04b780-1233-11eb-8729-637342fef70a.png)
This ONLY happens when importing a Device Template that contains a Data Query.

I have even tried to remove the Data Query from the bottom of the XML and the error still happens, so it is only referenced in the top part of the XML.
![image](https://user-images.githubusercontent.com/5603694/96484161-28f9f000-1234-11eb-9852-6e2f7956e7aa.png)

**Comment by TheWitness** [comment]
grab lib/import.php and try again.

**Comment by datatecuk** [comment]
Still the same error I'm afraid
![image](https://user-images.githubusercontent.com/5603694/96488024-52ffe200-1235-11eb-93bf-3349be9feaa7.png)

**Comment by TheWitness** [comment]
Try again.

**Comment by datatecuk** [comment]
Perfect, that has fixed the error, wow that was a quick fix.

**Comment by TheWitness** [comment]
It's Lunch time ;)

**Comment by datatecuk** [comment]
How far off is 1.2.15 from being released as the latest version?
This is the only issue we have come across so far with it so far.

**Comment by TheWitness** [comment]
Well, the more testing done by people like you, the closer it is.  We are now a month behind, and I keep saying no more, a day before more show up.
