### ISSUE TITLE
When syncing data collectors, a reindex event may be triggered unnecessarily

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3931]
Hey All 

I am having a weird issue and I see a descrpency between spine and netsnmp
I have some new devices in my lab around 400 of them I recently started noticing that a handful of them seem to always be set for recache

Digging furthure I see that the recache has been triggered because of  .1.3.6.1.2.1.1.3.0 this is a wireless modem and the OID puts out the uptime of the wireless connection and not the modem system uptime for what ever reason 

Here is the log 

```
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[609] HT[1] RECACHE: Processing 2 items in the auto reindex cache for 'IP'
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[655] HT[1] RECACHE: Processing 2 items in the auto reindex cache for 'IP'
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[613] HT[1] DQ[14] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4129044 < output: 4135832)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[613] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4129044 < output: 4135832)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[613] HT[1] RECACHE: Processing 2 items in the auto reindex cache for 'IP'
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[611] HT[1] DQ[14] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 1416513 < output: 1423302)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[611] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 1416513 < output: 1423302)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[586] HT[1] DQ[14] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4112543 < output: 4119352)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[586] HT[1] DQ[4] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4112543 < output: 4119352)
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[611] HT[1] RECACHE: Processing 2 items in the auto reindex cache for 'IP'
2020-10-09 15:07:19 - SPINE: Poller[1] PID[4082] Device[586] HT[1] RECACHE: Processing 2 items in the auto reindex cache for 'IP'
```

I also started seeing the following in the error log

```
2020-10-09 15:27:21 - POLLER: Poller[1] ERROR: Process being killed due to timeout! (commands, master, 1, 21242)
2020-10-09 15:27:19 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[642]
2020-10-09 15:27:19 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[670]
2020-10-09 15:27:19 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[694]
2020-10-09 15:27:18 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[661]
2020-10-09 15:27:18 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[611]
2020-10-09 15:27:17 - SPINE: Poller[1] PID[8933] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[664]
```

When I do a poll direct from spine I get the following 

./spine -R -H 329  | more
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0)
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0) [complete]
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0)
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0) [complete]
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0)
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0) [complete]
2020-10-09 15:29:33 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0)
2020-10-09 15:29:35 - SPINE: Poller[1] PID[18512] Device[329] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0) [complete]
2020-10-09 15:29:35 - SPINE: Poller[1] PID[18512] ERROR: Failed to get oid '.1.3.6.1.2.1.1.3.0' for Device[329]

But if I do a snmpwalk on that OID it is responding fine 

Spine v1.2.12
Cacti V1.2.12
NET-SNMP version: 5.7.2

**Comment by TheWitness** [comment]
Test ASAP.  This will force us to move ahead the release.

**Comment by bmfmancini** [comment]
Thanks Larry I should be able to test this on monday if I get a chance
earlier is I'll report back

**Comment by TheWitness** [comment]
Sooner the better, I don't want this bug hanging out there for too long.

**Comment by bmfmancini** [comment]
@TheWitness  

I tested this morning I grabbed the files off the 1.2.x branch same behavior is seen

**Comment by bmfmancini** [comment]
Should I try to rebuild the poller cache?

**Comment by TheWitness** [comment]
Yes.

**Comment by bmfmancini** [comment]
Ok just rebuilt the cache will report back soon

**Comment by bmfmancini** [comment]
@TheWitness  No change on my side

**Comment by TheWitness** [comment]
Are your PHP file replicating to the remotes?

**Comment by bmfmancini** [comment]
I will confirm for sure but I am pretty sure they did

**Comment by TheWitness** [comment]
It was buggered up on my system again.  Research tonight.

**Comment by bmfmancini** [comment]
Ok cool thanks !

**Comment by TheWitness** [comment]
Okay, take the latest lib/poller.php and do a full sync to your pollers.  This should get it fixed.

**Comment by TheWitness** [comment]
Related to #3916 and #3915

**Comment by bmfmancini** [comment]
Sorry man no Dice still coming in

**Comment by TheWitness** [comment]
So, the re-index warnings happen after replication still then?

**Comment by bmfmancini** [comment]
recache OID  warnings still come even after replication

**Comment by TheWitness** [comment]
Yea, just about to make an update.

**Comment by TheWitness** [comment]
Okay, should be fixed now.

**Comment by bmfmancini** [comment]
Ok testing now

**Comment by TheWitness** [comment]
Bump!

**Comment by bmfmancini** [comment]
Sorry I thought I replied

Sorry man I'm still seeing the same thing

**Comment by TheWitness** [comment]
Okay, take this watch and re-write it for your system, and then run it.  While it's running note the "assert" values.  Then, do a full sync to the remote, the value on the remote should go back.

```sh
 watch 'echo "Main Hosts";mysql -e "select * from poller_reindex where host_id=13" cacti;echo "Remote Host";mysql -ucactiuser -pcactiuser -hvmhost1 -e "select * from poller_reindex where host_id=13" cacti';
```

Output should look something like:

```
Every 2.0s: echo "Main Hosts";mysql -e "select * from poller_reindex where host_id=13" cacti;echo "Remote Host";mysql -u...  Fri Nov 27 10:30:39 2020

Main Hosts
host_id data_query_id   action  present op      assert_value    arg1
13      4       0       1       =       6       .1.3.6.1.2.1.2.1.0
13      6       0       1       <       590286159       .1.3.6.1.2.1.1.3.0
13      7       0       1       <       633714161       .1.3.6.1.2.1.1.3.0
13      8       0       1       <       633714235       .1.3.6.1.2.1.1.3.0
13      9       0       1       <       633714273       .1.3.6.1.2.1.1.3.0
Remote Host
host_id data_query_id   action  present op      assert_value    arg1
13      4       0       1       =       6       .1.3.6.1.2.1.2.1.0
13      6       0       1       <       639166433       .1.3.6.1.2.1.1.3.0
13      7       0       1       <       639166435       .1.3.6.1.2.1.1.3.0
13      8       0       1       <       639166437       .1.3.6.1.2.1.1.3.0
13      9       0       1       <       639166439       .1.3.6.1.2.1.1.3.0
```

**Comment by TheWitness** [comment]
You should notice that the Main collectors time should be back from before the last sync, and it should not be updated afterwards.  The only person writing that assert_value will be the remote data collector unless you have another collector pushing data into your production system, which would be a setup error I think.  For that, it might be good to log the connection attempts and where they are coming from.

**Comment by TheWitness** [comment]
If the later is the case, you might want to consider a more strict ACL on who can connect to what databases, if you don't have that already.  I don't want to jump to any conclusion here though.

**Comment by bmfmancini** [comment]
I am trying this now the thing is I have devices doing this that are on the Main poller

**Comment by TheWitness** [comment]
That's very odd then.  Might even be some device issue.

**Comment by TheWitness** [comment]
@bmfmancini, I'm marking this one closed as it was a real problem for remote data collectors, and that issue is resolved.  As far as main data collector based devices, I suggest a zone collision or some hardware issue.
