### ISSUE TITLE
[1.2.18] Poller Output Table not Empty

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [Cacti/cacti#4470]
Cacti 1.2.18 here. Tried 1.2.19 but it generates an [infinite loop](https://github.com/Cacti/cacti/issues/4469). So staying with 1.2.18 for now.

So there is one graph of one host (one rrd, two rras) which remains in the poller_output table after poll.
This started a few days ago, no idea what changed at that moment.
I've checked the RRD file, permissions are OK. The disk is not full....

I have narrowed it down to the following part in lib/poller.php and augmented it with some debugging:

```
    $f = 'cacti-rrd_update_array1-' . date('Ymd-His');
    file_put_contents("/tmp/$f", print_r($rrd_update_array, TRUE));

    /* make sure each .rrd file has complete data */
    $k = 0;
    $data_ids = array();
    foreach ($results as $item) {
      $unix_time = $item['unix_time'];
      $rrd_path  = $item['rrd_path'];
      $rrd_name  = $item['rrd_name'];

      if (isset($rrd_update_array[$rrd_path]['times'][$unix_time])) {
        if ($item['rrd_num'] <= cacti_sizeof($rrd_update_array[$rrd_path]['times'][$unix_time])) {
          $data_ids[] = $item['local_data_id'];
          $k++;
          if ($k % 10000 == 0) {
            db_execute('DELETE FROM poller_output WHERE local_data_id IN (' . implode(',', $data_ids) . ')');
            $have_deleted_rows = true;
            $data_ids = array();
            $k = 0;
          }
        } else {
          unset($rrd_update_array[$rrd_path]['times'][$unix_time]);
        }
      }
    }

    if ($k > 0) {
      db_execute('DELETE FROM poller_output WHERE local_data_id IN (' . implode(',', $data_ids) . ')');
      $have_deleted_rows = true;
    }

    /* process dsstats information */
    dsstats_poller_output($rrd_update_array);
    dsdebug_poller_output($rrd_update_array);

    api_plugin_hook_function('poller_output', $rrd_update_array);

    if (boost_poller_on_demand($results)) {
      $rrds_processed = rrdtool_function_update($rrd_update_array, $rrdtool_pipe);
    }

    $f = 'cacti-rrd_update_array2-' . date('Ymd-His');
    file_put_contents("/tmp/$f", print_r($rrd_update_array, TRUE));
```

Result is 
```
    ### before ### cacti-rrd_update_array1
    [/srv/www/cacti/rra/214/6392.rrd] => Array
        (
            [local_data_id] => 6392
            [times] => Array
                (
                    [1637435872] => Array
                        (
                            [traffic_in] => 379604614096292
                        )

                    [1637435922] => Array
                        (
                            [traffic_out] => 415722044441149
                        )

                )

        )

    ### after ### cacti-rrd_update_array2
    [/srv/www/cacti/rra/214/6392.rrd] => Array
        (
            [local_data_id] => 6392
            [times] => Array
                (
                )

        )
```

RRD looks ok to me
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "http://oss.oetiker.ch/rrdtool/rrdtool.dtd">
<!-- Round Robin Database Dump -->
<rrd>
        <version>0003</version>
        <step>300</step> <!-- Seconds -->
        <lastupdate>1637377544</lastupdate> <!-- 2021-11-20 04:05:44 CET -->

        <ds>
                <name> traffic_in </name>
                <type> COUNTER </type>
                <minimal_heartbeat>600</minimal_heartbeat>
                <min>0.0000000000e+00</min>
                <max>4.0000000000e+10</max>

                <!-- PDP Status -->
                <last_ds>379602156866748</last_ds>
                <value>NaN</value>
                <unknown_sec> 44 </unknown_sec>
        </ds>

        <ds>
                <name> traffic_out </name>
                <type> COUNTER </type>
                <minimal_heartbeat>600</minimal_heartbeat>
                <min>0.0000000000e+00</min>
                <max>4.0000000000e+10</max>

                <!-- PDP Status -->
                <last_ds>415457189990645</last_ds>
                <value>NaN</value>
                <unknown_sec> 44 </unknown_sec>
        </ds>

        <!-- Round Robin Archives -->
        <rra>
                <cf>AVERAGE</cf>
                <pdp_per_row>1</pdp_per_row> <!-- 300 seconds -->

                <params>
                <xff>5.0000000000e-01</xff>
                </params>
                <cdp_prep>
                        <ds>
                        <primary_value>NaN</primary_value>
                        <secondary_value>NaN</secondary_value>
                        <value>NaN</value>
                        <unknown_datapoints>0</unknown_datapoints>
                        </ds>
                        <ds>
                        <primary_value>NaN</primary_value>
                        <secondary_value>NaN</secondary_value>
                        <value>NaN</value>
                        <unknown_datapoints>0</unknown_datapoints>
                        </ds>
                </cdp_prep>
                <database>
                        <!-- 2021-11-18 02:10:00 CET / 1637197800 --> <row><v>2.0027813182e+05</v><v>1.2056160678e+06</v></row>
                        <!-- 2021-11-18 02:15:00 CET / 1637198100 --> <row><v>2.2026012872e+05</v><v>9.0331461645e+05</v></row>
                        <!-- 2021-11-18 02:20:00 CET / 1637198400 --> <row><v>2.5901786424e+05</v><v>9.3155006790e+05</v></row>
                        <!-- 2021-11-18 02:25:00 CET / 1637198700 --> <row><v>2.8265295589e+05</v><v>9.2401884634e+05</v></row>
                        <!-- 2021-11-18 02:30:00 CET / 1637199000 --> <row><v>2.6995818604e+05</v><v>1.2075598238e+06</v></row>
```

What also caught my attention is the poller spawning two instances of cmd, the second instance with min=max, not sure if that might be related. Also not sure if that wasn't always happening that way anyway...

```
wwwrun    5180 53.3  2.0 277496 81548 ?        R    19:45   0:00 /usr/bin/php -q /srv/www/vhosts/cacti/cmd.php --poller=1 --first=0 --last=280 --mibs
wwwrun    5202 52.6  0.9 214008 36068 ?        R    19:45   0:00 /usr/bin/php -q /srv/www/vhosts/cacti/cmd.php --poller=1 --first=281 --last=281 --mibs
```

**Comment by bmfmancini** [comment]
The Infinite loop is fixed on the 1.2.x branch

Which also addresses poller output table not empty as well

Try pulling down poller.php and lib/poller
PHP from the 1.2.x branch

**Comment by NotAProfessionalDeveloper** [comment]
Do we have an actual duplicated issue for this?

**Comment by netniV** [comment]
#4460 should be the original

**Comment by NotAProfessionalDeveloper** [comment]
Ah ok so both this as well as #4469 are duplicates.

**Comment by NotAProfessionalDeveloper** [comment]
I have replaced poller.php and lib/poller.php with the version 1.2.x in my current install of 1.2.8.
The graph in question still does not get populated, the row(s) remain in poller_output, but no warning notification/mail is sent anymore.... :-\

**Comment by NotAProfessionalDeveloper** [comment]
Never mind, the notification mail accompanying the error is back even with 1.2.x

**Comment by TheWitness** [comment]
Okay, I'm going to close this one as it's duplicate and resolved in the 1.2.x branch and for the 1.2.20 release.  Sorry about the inconvenience.

**Comment by NotAProfessionalDeveloper** [comment]
Hmm, as I wrote I have tried replacing poller.php and lib/poller.php with the version 1.2.x in my current install of 1.2.18, as someone suggested. It did not help.
Were there more fixes in the meantime (as compared to two weeks ago)?

**Comment by TheWitness** [comment]
Try this instead:

```sh
cd /var/www/html/cacti
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti.new
cp -rpf cacti.new/* cacti
chown -R apache:apache cacti
```

If you are using a Debian variant, instead of `apache` it'll be either `www-run` or something else.  Check that before doing anything.  If there are multiple processes running, kill them all.  Should be okay.  Where I have a Cacti it's almost 2M data sources and things finish up in about 100 seconds no problem using the patches.
