### ISSUE TITLE
Error PHP

### ISSUE THREAD

**Issue by nani81** [Cacti/cacti#4776]
Good morning, 
since a few days ago I am having several PHP failures that I have not found how to solve them with the version of cacti that I have.
Cacti: 1.2.19
OS: Red Hat
PHP: php.x86_64 - 5.4.16-48.el7

The errors are:
![Error PHP](https://user-images.githubusercontent.com/51642177/168533838-c8c453d9-0ec5-4ea6-93d7-a5ca2899352b.png)
![Stderr](https://user-images.githubusercontent.com/51642177/168533976-d7568467-bf22-41a8-b624-074bdb8d1621.png)
![Warning](https://user-images.githubusercontent.com/51642177/168534135-b9754ca3-718f-46e6-afe7-89ff6ff4d53d.png)

With the admin user notification warning disabled.
The admin user is enabled, has mail and the authentication is correct as well.
![Usuario admin](https://user-images.githubusercontent.com/51642177/168534801-31dbfb5f-efdb-431b-b979-60d8832b9103.png)
![Autentication](https://user-images.githubusercontent.com/51642177/168534813-b2f388ee-e5ca-4a64-bc02-08c7b44d26ab.png)

Thank you very much for everything.

**Comment by TheWitness** [comment]
I think all of these issues are fixed in the 1.2.x branch.  We've been in lockdown for two weeks now.  Just upgrade to that and you should be okay. Report back after you do.

**Comment by nani81** [comment]
Hi,
I upgraded a couple of months ago from 1.1.38 to 1.2.19.
I don't understand why these problems have been solved in 1.2.x. 
Making such a small upgrade as it is to 1.2.20 which would be the next stable release, I don't see it productive in my opinion.

Thank you for your answer, I will continue to see the changes that have been made to see if I can solve my problems.

Best regards

**Comment by nani81** [comment]
I have looked at the issues of version v1.2.20 in particular "issue#4529: Primary Admin account notifications may not work in certain cases".
And therefore I have made the change of the function "admin_email" in the file "lib/functions.php" and I still get the bug.

**Comment by TheWitness** [comment]
Update to version 1.2.21 which was released last night, and if the issue persists, we can again re-open this ticket.
