### ISSUE TITLE
Upon displaying a form with errors, the session error fields variable isn't cleared

### ISSUE THREAD

**Issue by luisanfe** [Cacti/cacti#5329]
# Describe the bug

When we brows to graph_view.php?action=tree from another tab we are showed the error "Action failed Sorry, we could not process your last action. Save Failed due to field input errors (Check red fields)."

## To Reproduce

1. Go to 'http://url_cacti/cacti/index.php'

2. Click on 'Graphs'

3. See error

## Expected behavior

Don't see any error message.

## Screenshots

![image](https://github.com/Cacti/cacti/assets/8067213/3de6028b-f716-4414-840c-68c44bf93da0)

## Desktop (please complete the following information)

- OS: Windows 10

- Browser Chrome, Firefox, Edge

- Version Lastone

## Additional context

The problem appeared after updating cacti from version 1.2.15 to 1.2.23 in CentOS 7 (3.10.0-1160.el7.x86_64)

**Comment by netniV** [comment]
Please provide the steps to replicate this and any errors that appeared in your logs at the time.

**Comment by luisanfe** [comment]
After logging into the application, when I click on the Graph tab, the message appears.
In the logs I don't see any special messages caused by the error.

**Comment by bmfmancini** [comment]
I'm not able to replicate this
What plugins do you have installed?

**Comment by luisanfe** [comment]
![Plugin](https://github.com/Cacti/cacti/assets/8067213/49334d4e-d31e-462b-93d4-481ffa8ff1c3)

**Comment by netniV** [comment]
I'm not seeing anything specific with the core of cacti that relates to this problem.  Can I suggest that you disable plugins and retest?  It may be worth disabling one at a time to work out which is causing you the problem.  

DO NOT UNINSTALL as this will remove any plugin specific data as well as removing the plugin.  If the problem persists after that, it may be then we need to look at uninstalling a plugin.  One of them states you need cacti >= 1.2.24 which may also not be helping.

Finally, if you still have the issue, it may be browser plugin related as these can sometimes inject fields/values, so try a clean/incognito session.

**Comment by luisanfe** [comment]
![Captura de pantalla 2023-05-30 112530](https://github.com/Cacti/cacti/assets/8067213/ee910ed8-51b7-419a-9997-67aca2037350)

**Comment by TheWitness** [comment]
So, the real question is when these messages start to appear, what form were you on last?

**Comment by TheWitness** [comment]
I've seen this issue.  The fix is quite easy.

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by netniV** [comment]
Hopefully, we are never setting that in the backend to report errors with fields after submission?

**Comment by TheWitness** [comment]
No.  It's all before rendering and happens as a result of the various `form_input_validate()` functions prior to `sql_save()`.  So, instead of Javascript validation that we would use today, it's all about the backend validation from the past.

**Comment by luisanfe** [comment]
I'm sorry but we have applied Fixing #5329 - Form errors persist after display but it hasn't solved the issue.

**Comment by TheWitness** [comment]
What page is causing the initial error?

**Comment by TheWitness** [comment]
You may have to log off and back on again.

**Comment by luisanfe** [comment]
Hello. Sorry for the delay. I  did log off and log on but the behaviour is the same.
I updated from 1.2.15 to 1.2.23 and the fist page that showed the error was the Graphs when I click on a device to see its graphs. After that, doing what your team suggested me I saw the same error in other pages.

**Comment by luisanfe** [comment]
Sorry, but it's not resolved.

**Comment by TheWitness** [comment]
Update to 1.2.25 otherwise known as the 1.2.x branch.  You updated two 1 release old.
