### ISSUE TITLE
[QA 1.3] - Graphs not shown in tree for "All" templates, but not for all trees.

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#6011]
# Describe the bug
I just upgraded to the latest commit:  

`877d8c13b (HEAD -> develop, origin/develop, origin/HEAD) QA: Remove the _2 from the variable.  It's confusing
`

## To Reproduce

in Graphs, select a tree with graphs assigned too the folder/tree item.. no graphs are shown when "All" is selected.  but If I choose the tmpleate name, then graphs are shown.

![image](https://github.com/user-attachments/assets/d07f22ef-21c8-44c2-a639-f4179de130f9)

Viewing "All"
![image](https://github.com/user-attachments/assets/578620fc-0a07-4643-8a65-82986d116888)

Checking "All" with Select all in the dropdown
![image](https://github.com/user-attachments/assets/4ca7311d-68c4-475d-9439-fb017c09a2c7)

**Comment by TheWitness** [comment]
Yea, it should be working better now.  I'm just wrapping up the feature now. Likely do all QA tomorrow, then parties for next two days. .

**Comment by dallenk** [comment]
Merry Christmas!

**Comment by TheWitness** [comment]
If it's working better.  Just close this.  There are other big changes coming later in the week and when @browniebraun and @xmacan get back from their breaks.

**Comment by TheWitness** [comment]
More updates this morning.  Pretty sure this should be fixed, but please try to reproduce when you get a chance to update.

**Comment by dallenk** [comment]
hmm..  behavior seems the same form me still on b0b3fb7d4

no graphs
![image](https://github.com/user-attachments/assets/716027a3-9270-4fb4-860a-1549d1e76244)

all graphs (after choosing "Check All"
![image](https://github.com/user-attachments/assets/0b8106a5-5506-4d18-b621-395c33f3eae8)

**Comment by TheWitness** [comment]
I made another update this morning.  Bouncing around on how to properly use the `??` operator in PHP.

**Comment by TheWitness** [comment]
Make sure you clear your browser cache before testing again.

**Comment by dallenk** [comment]
Sorry to bump this one, I know it's a huge work in progess., seems the "select all" option is gone, and still having issues with all selected.  cache has been cleared (positive this time :)

All selected
![image](https://github.com/user-attachments/assets/c444c6b7-363d-4073-9b66-686f919fdffc)

one template enabled
![image](https://github.com/user-attachments/assets/1f4e5881-0cb5-437a-b15b-08cfcc77ecce)
