### ISSUE TITLE
When purging RRD files, paths are not correctly handled

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#6168]
Cacti 1.2.x branch current
I deleted 60+K graphs
I run rrd cleaner and it finds 4748 rrd's to be deleted Total Size [MB]: 2963.59
I click Delete All
It says scheduling deletion but they are never removed. My rra folder size doesn't reduce. I scan again and they are still there.
If I select a few and manually delete those, they are not removed either.

**Comment by TheWitness** [comment]
Seems I fixed this in 1.3, but it's been delayed a while now.

**Comment by TheWitness** [comment]
Have you considered turning on auto-purge?  Moving this to a 1.3 issue @jdcoats

**Comment by TheWitness** [comment]
I think it's already fixed there too.

**Comment by jdcoats** [comment]
I do have autoclean on still does not delete the rrd files. Scanning > 1 week shows 483062 files 159040.08 MB to be removed but it never happens.

**Comment by jdcoats** [comment]
Touching this to keep open for 1.2x until 1.3x is ready for prod

**Comment by TheWitness** [comment]
@jdcoats, I've been distracted as you can tell.  Family and personal issues.

**Comment by xmacan** [comment]
@jdcoats PR created, please test

**Comment by jdcoats** [comment]
well.... it looks like it deleted a pile of active working graphs /me hates to rebuild all of my weathermaps again :S

**Comment by xmacan** [comment]
@jdcoats I'm sorry to hear that. My fix is small, It  only adds realpath to filename. I tested it and It worked well on my system.
Do you have enabled Structure RRDfile Paths?

**Comment by jdcoats** [comment]
as far i I can tell so far, it deleted all of my graphs so i have a fresh start but the poller recreates them same ids so i dont have to rebuild weather maps

**Comment by jdcoats** [comment]
yes structured paths

**Comment by xmacan** [comment]
Please remove any graphs and use rrdcleaner again. Select graphs for deleting or archiving and run SQL query
select * from data_source_purge_action limit 10;
show output

**Comment by jdcoats** [comment]
interesting
```
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [cacti]> select * from data_source_purge_action limit 10;
Empty set (0.000 sec)
```
yet rrdcleaner shows all of these current graphs (43648) datasources as deleted when they are not.

![Image](https://github.com/user-attachments/assets/bb2916d8-f1dd-4646-b997-f4d4b25a84a5)

**Comment by TheWitness** [comment]
@jdcoats, Ugh, but you have a backup right?

**Comment by xmacan** [comment]
@jdcoats I will fix it ASAP

**Comment by jdcoats** [comment]
i do have backup rra's, It's not that big a deal to lose the graphs at this time though. My rra folder had grown so large, im not sure id take the time to pick and choose which ones to restore :) I would have been very careful with this if it were a huge deal.

**Comment by jdcoats** [comment]
when we think its fixed, i may learn to splice some of the old back with the new a little :)

**Comment by xmacan** [comment]
@jdcoats It is fixed in 1.2.x branch. I will revise it in 1.3 soon

**Comment by jdcoats** [comment]
thanks!
