### ISSUE TITLE
back button not working

### ISSUE THREAD

**Issue by c0sm1n** [Cacti/cacti#707]
I'm having and issue where the browser back button does not return to the previous page in certain instances.

graphs -> Preview View -> click on the 'Graph Details, Zooming and Debugging Utilities' icon on a single graph works but when i click the browser back button to return to the previous page, it has no effect. 
same experience in graphs -> List View -> click on interface to view graph. browser back button does not return back to the previous page/list.

I'm running version 1.1.6 with a Classic theme and was able to replicate using both Firefox and Safari

**Comment by cigamit** [comment]
Resolved, please test.

**Comment by cigamit** [comment]
Going to close.  It seems to be working on my environment pretty well.

**Comment by Hyllegaard** [comment]
This does not appear to be working as intended.
Running 1.1.7 on ubuntu 16.04, and viewing from Firefox and Chrome on windows.
The URL in the address bar changes, but the page is not refreshed. This happens when browsers back button is pressed, backspace on keyboard and "back" button on mouse.

**Comment by espro** [comment]
1.1.10 here, still an issue with latest Chrome and Firefox on Mac. One page access results in two requests. E.g., hitting back twice will work

**Comment by c0sm1n** [comment]
doesn't work in 1.1.12 either. Still need to hit back button twice.

**Comment by Learloj** [comment]
I'm having the same issue in 1.1.28; when I go to Graphs and hit the 'time graph view' of any graph, pressing back only changes the URL, but not the page. After 3x hitting back, the page refreshes and  I'm back at index.php (and not the graph overview I got to when clicking 'Graphs'). I've tested with Google Chrome 63.0.3239.84 on macOS Sierra.

**Comment by Feklar22** [comment]
I was able to get the back button to start working by editing a javascript file.

include/layout.js
I added:
window.onpopstate = handlePopState;

to function ajaxAnchors() after these lines of code:
"$(window).on('popstate', function(event) {
                handlePopState();
        });"

**Comment by netniV** [comment]
Do you have a pull request or difference file?

**Comment by Feklar22** [comment]
I don't and really am not sure how to make a diff file.  Here is the full function that I edited in include/layout.js, it started around line 1407 for me.

> function ajaxAnchors() {
>         $('a.pic, a.linkOverDark, a.linkEditMain, a.hyperLink, a.tab').not('[href^="http"], [href^="https"], [href^="#"]').unbind('click').click(function(event) {
>                 event.preventDefault();
>                 event.stopPropagation();
> 
>                 /* update menu selection */
>                 if ($(this).hasClass('pic')) {
>                         $('.pic').removeClass('selected');
>                         $(this).addClass('selected');
>                 }
> 
>                 /* update menu selection */
>                 if ($(this).hasClass('lefttab')) {
>                         $('.lefttab').removeClass('selected');
>                         $(this).addClass('selected');
>                 }
> 
>                 /* update menu selection */
>                 if ($(this).hasClass('righttab')) {
>                         $('.righttab').removeClass('selected');
>                         $(this).addClass('selected');
>                 }
> 
>                 /* execute an ajax request to load the data */
>                 href = $(this).attr('href');
> 
>                 if (href == '#') {
>                         return false;
>                 }
> 
>                 if (href != null) {
>                         pageName = basename(href);
>                 }
> 
>                 loadPage(href);
> 
>                 return false;
>         });
>         $(window).on('popstate', function(event) {
>                 handlePopState();
>         });
>         $('#filter, #rfilter').keydown(function(event) {
>                 if (event.keyCode == 8 && $(this).val() == '') {
>                         handlePopState();
>                 }
>         });
>         window.onpopstate = handlePopState;
> 
> }

I just added window.onpopstate = handlePopState; to the end after tinkering and noticing that javascript wasn't entering into either of the previous two states when I would click on the back button or use the back button on my mouse.

**Comment by netniV** [comment]
Oh, forgot to ask what version of cacti you are running?

**Comment by Feklar22** [comment]
1.1.36 currently,  been having the issue since upgrading to 1.x though.

**Comment by netniV** [comment]
That's OK, just wanted to make sure where I compare your code against 👍
